<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon_Search</name>
   <tag></tag>
   <elementGuidId>d7f399e5-1b77-4030-ab0a-8c0a4b8a81f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div/div/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9ebf4a40-fe5f-4418-b58b-d628c3f503d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon text-darkblue fa fa-search fa-2x</value>
      <webElementGuid>9d701124-a182-41ce-a18f-e2912334f764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-76196e6bb566205bcd502147869ed97b</value>
      <webElementGuid>0bca9398-af65-49ab-a0f1-69a3a7544088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fa-search ')]</value>
      <webElementGuid>3b22b6c1-2bc0-4298-9210-8b44d35e5404</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' fa-search ')]</value>
      <webElementGuid>e84f497a-e2de-4651-a11c-bdeea3039230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
