<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dd_mm_yyyy_StartDate</name>
   <tag></tag>
   <elementGuidId>0f7fbcf7-07a6-4f5e-a6d6-56cb34f6cab6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@data-container = '') and (position() = 1)]/*[@data-block = 'SurveyKunjungan.Item_DatePicker']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-container=&quot;&quot;]:nth-child(1) > [data-block=&quot;SurveyKunjungan\.Item_DatePicker&quot;] .form-control.text-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a62b106-7c51-41f7-bdfd-27a76901c039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-input OSFillParent</value>
      <webElementGuid>e57e8932-4e64-4ebf-b557-b328f8e0a772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>855eac28-ec22-44b0-8cc0-c06d864b8a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>d3089a24-0be2-454a-b151-afef81d39563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98d62cad-e644-4e66-9d1d-486a1fe3def0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bd509980-8442-4e4c-af92-a5aff3766b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b1-b4-Input_TextDate</value>
      <webElementGuid>b850f0be-b1b8-48fe-b592-5e87f940017a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2fd88bd7-307c-4039-b359-985f4a6b9c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-40113bcb202bc02859ee67a95a9bb293</value>
      <webElementGuid>2116c3ec-e69d-4d18-bb4b-481533947066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@data-container = '') and (position() = 1)]/*[@data-block = 'SurveyKunjungan.Item_DatePicker']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ')]</value>
      <webElementGuid>daf168bc-9869-4dd7-b0cd-9ff5cb27db28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@data-container = '') and (position() = 1)]/*[@data-block = 'SurveyKunjungan.Item_DatePicker']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ')]</value>
      <webElementGuid>9d7dabdb-1c99-48ad-b4e8-1b691d723194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy' and @id = 'b4-b1-b4-Input_TextDate']</value>
      <webElementGuid>cd00f9ab-073a-4bd9-9d82-4c7e22a6dbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
