<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dd_mm_yyyy_EndDate</name>
   <tag></tag>
   <elementGuidId>b78fc96e-3857-42cd-977d-b846e0c0816d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ') and (@readonly = '') and (@placeholder = 'dd/mm/yyyy') and (@type = 'text') and (@value = '')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form-control.text-input[readonly=&quot;&quot;][placeholder=&quot;dd\/mm\/yyyy&quot;][type=&quot;text&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70e3b975-55e0-464c-b5a4-2cfa491e9e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-input OSFillParent</value>
      <webElementGuid>ce5b435e-5973-4b84-91c2-4363c18546f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a1c5e3d-c831-4151-90bd-474b5f7743bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>3ae5fcc3-8548-4d18-86bd-9bf0f39d07ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ae23f26-c92e-42d3-b61d-99955b35eafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2da6ffb9-bba8-41c9-bd27-a641e10aa415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-b1-b5-Input_TextDate</value>
      <webElementGuid>447af06a-1ca9-4a1b-af91-036dafb0e38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0f00bdf-ec40-4630-b32f-9c22ad520888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b8e5bdeaf6b5a8be3dd1c2738a9caa73</value>
      <webElementGuid>e0c12168-1b37-42ed-81e4-23293d5ab990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ') and (@readonly = '') and (@placeholder = 'dd/mm/yyyy') and (@type = 'text') and (@value = '')]</value>
      <webElementGuid>0a5d18f0-0900-4c04-bc46-4f0fe038d03d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-control ') and contains(concat(' ', normalize-space(@class), ' '), ' text-input ') and (@readonly = '') and (@placeholder = 'dd/mm/yyyy') and (@type = 'text') and (@value = '')]</value>
      <webElementGuid>84f32fd2-8e3d-45dc-ab29-3c3f05288bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'dd/mm/yyyy' and @id = 'b4-b1-b5-Input_TextDate']</value>
      <webElementGuid>2237484e-f274-4755-b108-4bdf26e6248e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
