<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Back_2</name>
   <tag></tag>
   <elementGuidId>db3abdd7-6b61-492e-a7d7-d0b1f2a8442d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[1]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2942c0b6-8987-4bf1-8970-28c6743231f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-back</value>
      <webElementGuid>c20ed0d2-9b3f-4e6c-beb3-603bc8cb574d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>613b5427-20b2-4c7d-859b-764e8fe2aea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Back</value>
      <webElementGuid>84f022e7-5d57-46c8-a5f8-b376b3c23edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$b3&quot;)/div[@class=&quot;margin-bottom-m&quot;]/button[@class=&quot;btn btn-back&quot;]</value>
      <webElementGuid>be83d6d1-3f50-488f-8dac-b5496e8fb357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>07ab0d51-5fc7-4119-891e-36b30b89a09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b3']/div/button</value>
      <webElementGuid>3de22352-4de9-424d-9e35-607de3d47195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ops Risk CBU Supervisor'])[1]/following::button[1]</value>
      <webElementGuid>ade46116-67a3-498a-b000-65e7ba6b02b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADHY RUSMALA SURNANTO'])[1]/following::button[1]</value>
      <webElementGuid>fe17fa3c-7f80-48ef-b508-946e64dafe3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Bisnis :'])[1]/preceding::button[1]</value>
      <webElementGuid>e543acea-67ad-4e1e-8c47-b3f0fca780ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4bbfcd95-d9d9-443f-b8b3-694c86a80e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '  Back' or . = '  Back')]</value>
      <webElementGuid>8f0fa05c-73d6-4d06-b12e-9d4f876ae64c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
