<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assign_Checkbox2</name>
   <tag></tag>
   <elementGuidId>0fddaad6-4f1d-4226-8bfe-6930f04d8f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div/div[2]/div[1]/table/tbody/tr[5]/td[1]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-l1_0-395_1-Checkbox2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>907d1248-b7bf-4db4-83a7-67ec6000b1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f2c4d04-afa8-4f92-a0c3-2ef0df889623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>082d837c-8cf0-4c04-aa1e-b2d8dd2edc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-l1_0-395_1-Checkbox2</value>
      <webElementGuid>a2ad99c9-8c2b-4724-ab5a-0a585efd5029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-l1_0-395_1-Checkbox2&quot;)</value>
      <webElementGuid>f420e279-852f-4812-acd2-88deccfcb7d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-l1_0-395_1-Checkbox2']</value>
      <webElementGuid>179da968-6687-4c87-a2f1-d605f14f7fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-$b1']/div[2]/div/table/tbody/tr[2]/td/span/input</value>
      <webElementGuid>8f650b17-911b-4c58-9f31-83fbd7e9bbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/span/input</value>
      <webElementGuid>f97d60f7-b12d-4478-8941-e73984dadb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b1-l1_0-395_1-Checkbox2']</value>
      <webElementGuid>253b5788-2d03-42f7-a61c-55bbcd000ac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
