<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b2-l4_0-194_0-Input_AirwayBill</name>
   <tag></tag>
   <elementGuidId>78d9ea7f-18ae-4b16-9e35-716444df22c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div/div[3]/div[1]/table/tbody/tr/td[6]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-header=&quot;Airway\ Bill\.\/\ Alamat\ Email&quot;] [type=&quot;text&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46630548-59d0-414c-8814-a7def225fe7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>fc894804-8ba3-4cd8-a8cb-bb66f81cce1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc176970-d1d6-44e7-9f10-7ba2c00f458b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1164e3e0-ddc7-4044-be9d-8c087b5a4097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>bdd83d66-a9b4-4976-b616-11c00d0babfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l4_0-194_0-Input_PICPengiriman2</value>
      <webElementGuid>3f6682c0-0b0c-4d10-90a4-9578c0a52d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-88e0b8c655eed9fd05d33b0b70c04aaa</value>
      <webElementGuid>077e5cf6-5008-44af-89b7-0512ec169eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-header = 'Airway Bill./ Alamat Email']//*[(@type = 'text') and (@value = '')]</value>
      <webElementGuid>9f3fbe83-7a37-45fa-8e3f-7c59c4a727e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-header = 'Airway Bill./ Alamat Email']//*[(@type = 'text') and (@value = '')]</value>
      <webElementGuid>0ab2362e-85e3-42ce-b530-9bea9b128ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-b2-l4_0-194_0-Input_PICPengiriman2']</value>
      <webElementGuid>491e3bc6-b199-4abb-b742-f6639dd47a65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
