<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select Status</name>
   <tag></tag>
   <elementGuidId>8833cf5e-672d-4906-af81-e98df5b11ccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[1]/div/div/div[3]/div[2]/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-Dropdown3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>467303d5-48d1-49fa-92f8-28bda6351f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>8290010d-e93d-4d07-aba3-c4a133777ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0279cf16-049f-4319-8ccd-5432dad038a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-Dropdown3</value>
      <webElementGuid>537a3bb9-979a-4fc9-8b77-9e29d095b962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StatusMENUNGGU PERSETUJUANDIKEMBALIKANDISETUJUI</value>
      <webElementGuid>0355f520-2580-4e3f-98db-2bf34acd6776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-Dropdown3&quot;)</value>
      <webElementGuid>f6f1be29-189c-4339-b95f-414872f41a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b1-Dropdown3']</value>
      <webElementGuid>20d18466-754c-4f3e-89b6-5bae12b0acca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-Dropdown3-container']/select</value>
      <webElementGuid>40dcf1cc-1dd3-4ba3-9180-81ce7fde7be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>18f9b2f1-9e13-4e9e-b4f5-79721fb94744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang :'])[1]/following::select[2]</value>
      <webElementGuid>3a0719e4-339d-459e-b3ae-f366607414cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[2]</value>
      <webElementGuid>d44f0be1-d334-45f1-8c7f-9dbadc485a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/select</value>
      <webElementGuid>c259205b-0f94-42cf-8c76-d18bf67fdab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b1-Dropdown3' and (text() = 'Select StatusMENUNGGU PERSETUJUANDIKEMBALIKANDISETUJUI' or . = 'Select StatusMENUNGGU PERSETUJUANDIKEMBALIKANDISETUJUI')]</value>
      <webElementGuid>4e93387e-76fb-44b8-a9a6-fa3fcffc11cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
