<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Survey Pengurus_Checkbox</name>
   <tag></tag>
   <elementGuidId>182782f2-bbb7-4256-a935-8104bda7fe4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[4]/article/div/div/div/div/div[2]/div[2]/div[2]/span[1]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-175_3-b11-b2-l2-385_1-Checkbox1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e36021c9-7c8d-4b75-a964-edeed97e08e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b4a90c6b-071e-414c-b015-13f139ee068a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>20e0d80a-341e-488a-b414-2457d4a519ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-175_3-b11-b2-l2-385_1-Checkbox1</value>
      <webElementGuid>e4e7182d-be42-437d-93fb-ce1902017051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-175_3-b11-b2-l2-385_1-Checkbox1&quot;)</value>
      <webElementGuid>34a41315-5d73-4a43-90df-463876ac5698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-l2-175_3-b11-b2-l2-385_1-Checkbox1']</value>
      <webElementGuid>e997231a-976c-446e-8313-073e7ea48245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-175_3-b11-$b2']/div[2]/div[2]/div[2]/span/input</value>
      <webElementGuid>b2807ee6-bc94-41d2-b4b0-200f9060ec95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>25688076-7615-4147-8109-859536be6e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-l2-175_3-b11-b2-l2-385_1-Checkbox1']</value>
      <webElementGuid>2bae0981-e7e8-4337-9cfe-f320f48bce9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
