<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Survey Checkbox1</name>
   <tag></tag>
   <elementGuidId>241e4ff2-acc9-4a96-bfe4-b147c555c6ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-l2-178_3-b11-b2-l2-343_1-Checkbox1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[3]/div[1]/section/section/div/div/div[4]/article/div/div/div/div/div[2]/div[2]/div[2]/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eafa99cc-e274-4940-b748-a84ec7332283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>78b96b16-1c29-45b9-a5c2-09f18006c2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86669d9d-f033-4adc-b0f0-1500bcd4bc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-178_3-b11-b2-l2-343_1-Checkbox1</value>
      <webElementGuid>029ab28e-c520-4334-8bf8-f0bf2613b98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-l2-178_3-b11-b2-l2-343_1-Checkbox1&quot;)</value>
      <webElementGuid>c944f00c-5ca8-4d75-a4b4-030b5c0cb0b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-l2-178_3-b11-b2-l2-343_1-Checkbox1']</value>
      <webElementGuid>206bdbb2-8401-4c12-a5bf-750262925b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-l2-178_3-b11-$b2']/div[2]/div[2]/div[2]/span/input</value>
      <webElementGuid>9bb5fb4c-b9b6-4b9b-8923-c775c307f947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>4e7f95d0-901c-48d7-a2b7-ab132ecc8cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-l2-178_3-b11-b2-l2-343_1-Checkbox1']</value>
      <webElementGuid>c6b76b81-9aab-43cb-a0a2-8dbb0130868c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
