<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Draft_RBU</name>
   <tag></tag>
   <elementGuidId>f48534fe-f031-4e52-8334-834b5c04cf0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[2]/div[1]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn.btn-custom--btn-amberorange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c535d61-7ba9-4fc6-858c-4b6d5613fcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-custom btn-custom--btn-amberorange OSFillParent</value>
      <webElementGuid>be68fd7f-0a49-4f0d-9e68-4f8adceead0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f96fa4e8-4cf2-45db-8b68-14020c5c03b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-ButtonDraft2</value>
      <webElementGuid>a3c3acb6-d727-4cb7-8353-d7e75a0ac521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>0817aa7d-4171-4eaf-a1da-c9164b7a3195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6122b38b6624c96f5ffd2b7a811d98fd</value>
      <webElementGuid>dfa27956-d355-4733-992f-154a5c2ab6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-custom--btn-amberorange ')]</value>
      <webElementGuid>9ef7e1a5-8cb3-4603-9b23-dc80df9ee66a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-custom--btn-amberorange ')]</value>
      <webElementGuid>ceea67d1-c45f-4125-acc5-266ba496aeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b4-ButtonDraft2' and (text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>27b06d28-47c4-4ede-8b91-cde4706a1361</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
