<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_Telepon</name>
   <tag></tag>
   <elementGuidId>4b39575e-8a6e-494b-bd0f-956169ac16ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[3]/div/div[2]/div/div/div[2]/div/form/div/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90c9b94c-7646-45ae-8491-22290c7915ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4eae4cb9-b55f-4353-ac6a-0983bb5ca6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioButton1-input</value>
      <webElementGuid>8780bd3d-9781-47cc-a1cd-df05f2e79895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>1625f163-4e1b-4bd6-aa60-0281ad527415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioGroup1</value>
      <webElementGuid>08847e10-b3d2-487d-b501-af9e14a728be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>cdf8c56f-44cb-43c1-a7e0-e5d4a6332fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-071af4a3c442c653244458a2d69d3efe</value>
      <webElementGuid>f7706d22-00ea-44b0-bf06-6db6d2a19d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioGroup1']</value>
      <webElementGuid>893ba997-1349-40e4-b5e1-5a52d7100aec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioGroup1']</value>
      <webElementGuid>954c03d4-bffa-49fa-9ead-5de1acebe1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioButton1-input' and @name = 'b4-l2-28_2-l2-46_1-b2-b12-l1-65_0-RadioGroup1']</value>
      <webElementGuid>ce6bc64a-6ca1-44b6-b7f8-31f30366a4e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
