<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai</name>
   <tag></tag>
   <elementGuidId>934ed724-1055-444b-b201-07b3ee0410d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[2]/div/div[2]/div/div/div[1]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f87e5b32-0e99-4663-a831-0a6ec5e748bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f32565f1-ce0c-4726-8b7d-3d3a2ca6b7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioButton1-input</value>
      <webElementGuid>65cd809b-ec99-422b-9af5-f35b7eb0e135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>28c8e3b7-444c-4aad-816b-226d420c419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioGroup1</value>
      <webElementGuid>281d382b-7465-4730-95cf-362e189bf218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>46eb71c3-432b-40cb-9875-7d4459e85891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d5d45f7ecee9b9e0c31cfe737da3301c</value>
      <webElementGuid>66c503ac-7dd0-4483-82c3-60a6cf1c5dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioGroup1']</value>
      <webElementGuid>591c49b7-13e3-4911-90cc-cd3eaa8551b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioGroup1']</value>
      <webElementGuid>28416099-d859-40ac-aec4-dc9648013234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioButton1-input' and @name = 'b4-l2-28_1-l2-39_6-b2-b8-b3-l1-95_0-RadioGroup1']</value>
      <webElementGuid>1abf8fee-635e-44ee-abfd-c4f247a514de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
