<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai</name>
   <tag></tag>
   <elementGuidId>9e5bfc70-f59d-4df2-81f6-0f7fcaa99970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[2]/div/div[2]/div/div/div[2]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fad5115-215a-42b5-ab22-2505f2025f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1aa3da1f-1a59-4793-b5dc-0c41330e0afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioButton1-input</value>
      <webElementGuid>f14c7790-1722-459c-b8d2-4be9d848d00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>6713bdc4-9ed1-4ab0-8a14-57af276aad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioGroup1</value>
      <webElementGuid>616ce5d4-45bc-4cfd-8924-7ceef935aab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>518c622b-2746-44e0-80d4-1c4bdca1aefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a6242b121cf27dfef1401547ff61606e</value>
      <webElementGuid>6855a193-c439-412c-b4aa-212fd2432497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioGroup1']</value>
      <webElementGuid>01cca4be-015c-4120-937d-a2bddbd055ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioGroup1']</value>
      <webElementGuid>e09a30e4-1141-43a2-a987-dc18a642dc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioButton1-input' and @name = 'b4-l2-28_1-l2-39_8-b2-b8-b3-l1-99_1-RadioGroup1']</value>
      <webElementGuid>933af3ba-d9d5-4fa7-b960-21198e413590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
