<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_1</name>
   <tag></tag>
   <elementGuidId>bdd1f818-fada-41a9-8ba8-6b7482976553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[2]/div/div[2]/div/div/div[3]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f078595-b96a-41d2-94aa-8c3d1a462be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>33df5473-59dc-4286-b1eb-5b4562038f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioButton1-input</value>
      <webElementGuid>192cd087-d080-4d90-8af8-00ccb393f78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>1b6b891c-9782-4353-bd0d-89aaedd44521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioGroup1</value>
      <webElementGuid>1edf763b-76bf-43b4-babc-4ad96f7badec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>26f3ca12-daf5-4e69-a9bf-bd2a1ba3135d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-55167d983a425f4aeb7572df1533dadb</value>
      <webElementGuid>1293679a-6e2e-48b7-83ea-9b7aadac4c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioGroup1']</value>
      <webElementGuid>0e338cfd-8fd2-44aa-8685-d40ff16073dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioGroup1']</value>
      <webElementGuid>ec5424d9-3382-4ea7-9164-28351ca3cf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioButton1-input' and @name = 'b4-l2-28_1-l2-39_10-b2-b8-b3-l1-103_0-RadioGroup1']</value>
      <webElementGuid>88f28613-2cc6-4f9e-9206-dcd539975835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
