<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_2</name>
   <tag></tag>
   <elementGuidId>f448cd3d-169d-4a69-bfb2-1dd54eb3fc49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[2]/div/div[2]/div/div/div[5]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94f74978-94df-4d69-8b62-04a133363bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6d2e224e-03e1-4809-979d-36e2ade2866d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioButton1-input</value>
      <webElementGuid>12187d90-0bbf-47a4-820c-6f83f0ac577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>6baa4afd-21ed-4eef-908e-f0a607b09414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioGroup1</value>
      <webElementGuid>1ae6ce01-d187-45c7-95b1-41a8d15570f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>0af8b9b0-b7d5-4f01-a887-42d19bb86e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8ff727d8cf1e4d1d2dfc3282b95dc80a</value>
      <webElementGuid>f0d967ab-5b62-4744-972e-96d596aeed5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioGroup1']</value>
      <webElementGuid>138d72f2-053e-49c5-9468-67e3d8d44a88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioGroup1']</value>
      <webElementGuid>8ea853b0-0e2a-4f42-b411-babe3217b795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioButton1-input' and @name = 'b4-l2-28_1-l2-39_14-b2-b8-b3-l1-111_0-RadioGroup1']</value>
      <webElementGuid>5466655b-7375-4f45-9982-dc38dbeac286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
