<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Sumber Informasi 1 __1</name>
   <tag></tag>
   <elementGuidId>6cf95752-73bd-46d1-9248-e071dc7e1dec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;AM&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[1]/div/div[2]/div/div/div[1]/div/form/div/div/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>763ec561-a2c5-4387-af48-e1367a07125b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>3e68f28f-24e1-44ca-b6b7-118e7c3ad707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2052eeb-b75a-4bc0-8fd4-986daf4ac4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2058afc-1a90-4547-b18a-b55d5984309e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ab6c482d-9b26-4f85-a7b8-8800536ac7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AM</value>
      <webElementGuid>e2de70b1-8af7-402c-a8af-b04d01fb840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_9-b2-b1-Input_QuestionAnswerValue</value>
      <webElementGuid>dd38122b-869b-4f7d-a321-94c25e015bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3f81271ee3450256daed39a83f18a8b6</value>
      <webElementGuid>024ce791-b93d-4ace-8730-0830c3d856d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'AM']</value>
      <webElementGuid>6fc98f0c-7206-4728-a7b4-708d007318d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'AM']</value>
      <webElementGuid>a74e11cb-4b0a-4b00-a92d-526d1de84fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b4-l2-28_0-l2-29_9-b2-b1-Input_QuestionAnswerValue']</value>
      <webElementGuid>b7f2afac-982f-4a35-b436-9977fd90bc21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
