<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ya</name>
   <tag></tag>
   <elementGuidId>e10644e0-8272-4968-b7f4-a265537b2a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[1]/div/div[2]/div/div/div[3]/div/form/div/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c14fe2fb-2f47-41d1-be8b-ac270f751157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>396b8cdb-2f94-4bc9-b559-49cf90d3345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioButton1-input</value>
      <webElementGuid>7a2d737d-1c38-429c-b78c-6e756408a31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>ef231e2f-2816-441d-8856-405b6518195d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioGroup1</value>
      <webElementGuid>3fce5e26-d55d-4857-b5a2-b6f292d7c4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>8cf4cb1b-7aea-486e-809d-4d22540eb739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5e6c3713b8413564e4cc820a49bed00b</value>
      <webElementGuid>d6681fc5-812d-461f-8c50-8d76912a7e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioGroup1']</value>
      <webElementGuid>f450c9d2-be71-43cb-97ea-30bb367a0c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioGroup1']</value>
      <webElementGuid>ef49ec04-abe7-4ca5-a036-4eab499db2fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioButton1-input' and @name = 'b4-l2-28_0-l2-29_2-b2-b12-l1-59_0-RadioGroup1']</value>
      <webElementGuid>f3af8912-3f8f-45a6-8acd-d2d5cb2d44c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
