<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ya_2</name>
   <tag></tag>
   <elementGuidId>318f5a19-893f-4e94-a2fc-729a8e8fe780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[1]/div/div[2]/div/div/div[9]/div/form/div/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d651ea6-8bc0-4905-b68e-f549d5347872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>80fcb000-aadf-46c4-bb47-a25a1d3fa61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioButton1-input</value>
      <webElementGuid>91d24d7c-8d92-4d80-b6f3-4c6e4418621d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>cea4bb79-7ed5-463d-ae04-53092a7ac1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioGroup1</value>
      <webElementGuid>e245570e-ba29-4803-82c7-b0bbe4cdce3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>e0d9ac44-85b1-458e-b3db-a50669d86d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-665733eef71163fe3b752935e68f9e23</value>
      <webElementGuid>6858919a-777e-4d72-b6c4-17a294e5e162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioGroup1']</value>
      <webElementGuid>98ad5365-c95b-4451-b7ca-8c24f34e3b48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioGroup1']</value>
      <webElementGuid>bc279acf-f50c-4128-ac1f-562852488dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioButton1-input' and @name = 'b4-l2-28_0-l2-29_8-b2-b12-l1-63_0-RadioGroup1']</value>
      <webElementGuid>5444658b-e246-48ae-bc7a-f24c11c3f403</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
