<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ya_1</name>
   <tag></tag>
   <elementGuidId>5926aed7-46b6-4735-b4fa-29a0061c4ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[1]/div/div[2]/div/div/div[6]/div/form/div/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ae0d26f-563f-4507-b919-47317820e537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f9187ee8-a850-4a0f-990b-1192407f7e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioButton1-input</value>
      <webElementGuid>221155ee-af7b-43ad-a85e-c76b7a69caf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>6b5a3e5a-1a6c-4a30-8963-d47fb2f98059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioGroup1</value>
      <webElementGuid>03c670ad-4fc1-4538-a465-9f25697f2506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>0af8fe9f-2b52-4317-8441-aa9858563265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-440f25c488335be53cdde8b555270863</value>
      <webElementGuid>1f8cf8c3-72ce-40f4-91d6-b753a38b52cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioGroup1']</value>
      <webElementGuid>7e8a7f9c-8c03-47b6-9d53-50c0f065c9f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioGroup1']</value>
      <webElementGuid>92c2d400-3e98-4ccf-80b6-273966c115bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioButton1-input' and @name = 'b4-l2-28_0-l2-29_5-b2-b12-l1-61_0-RadioGroup1']</value>
      <webElementGuid>b4811523-4570-46f2-9f4f-c75751726068</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
