<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_Alamat</name>
   <tag></tag>
   <elementGuidId>e46d508a-69f0-4d89-9552-2c2e8553b031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[3]/div/div[2]/div/div/div[1]/div/form/div/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ec93340-71d7-4650-b12b-c5c66708ff75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e1577ec8-4444-4f3b-93e1-3e5cf0bab197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioButton1-input</value>
      <webElementGuid>1d6f19d8-6186-4252-9f7a-a7d26295a045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>1d4c20a6-20ef-4478-84b0-46b072f83e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioGroup1</value>
      <webElementGuid>c428f1db-e17b-4169-a41c-29079260b050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>880bb0ea-0f48-4b91-ab85-66ef58cb228f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-51201beb870322be0d74034859da348a</value>
      <webElementGuid>056909ba-8864-48cd-aa32-ac39acaf604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioGroup1']</value>
      <webElementGuid>43116f69-02e3-4df5-9c85-393108a5aa56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioGroup1']</value>
      <webElementGuid>f7f8a6aa-bdae-4a12-9716-eb358eaceadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioButton1-input' and @name = 'b4-l2-28_2-l2-46_0-b2-b12-l1-64_0-RadioGroup1']</value>
      <webElementGuid>442a0f94-2993-4af7-84e5-70c485e83c7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
