<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai_1</name>
   <tag></tag>
   <elementGuidId>b2339d9a-d6fc-4d8d-afcb-4e694aea0591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div/div[2]/div/div[2]/div/div/div[4]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0441d4f7-61a0-4997-860e-bf07e082b171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>399b2b25-f376-4d6b-bd02-61f222a26d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioButton1-input</value>
      <webElementGuid>03bc3036-8b8b-485c-9ca4-ae890f709b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>27944aa5-d280-4d18-9d9a-e4265b52b4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioGroup1</value>
      <webElementGuid>21774ef2-24be-48fe-96b8-9d8a4416e513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>4c1e391d-d47b-455e-8b03-fc33274d598a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-36f127ecd1de185687d50ae40a3455db</value>
      <webElementGuid>df164d2b-a287-4f49-922e-f26504636a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioGroup1']</value>
      <webElementGuid>42bb16cd-373a-4ce5-ae7f-3a4c12025681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioGroup1']</value>
      <webElementGuid>b3345a0a-eb1e-45cb-b1d4-89b7805fb01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioButton1-input' and @name = 'b4-l2-28_1-l2-39_12-b2-b8-b3-l1-107_1-RadioGroup1']</value>
      <webElementGuid>e8c7e8e1-a101-46c2-852a-de10c061dbd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
