<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan Hasil Survey</name>
   <tag></tag>
   <elementGuidId>c2776e06-463c-4aff-96b7-754353bdf7d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-textarea=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-textarea = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dba62c31-ac51-4ec0-8fa0-afe39e601e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>d9333acd-c6b1-4619-a03b-8e280c97bd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>29da6d43-9462-48cf-86aa-99caef4e984a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength_input</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ae6aff00-1f84-4941-a69a-913e2670dbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>c8675169-235a-4f24-9b49-77613c415edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b4-l2-28_2-l2-46_6-b2-b2-TextArea_Answer</value>
      <webElementGuid>b8bf1db1-b61d-4db4-a0cd-e82a23629777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0983327a1988361bf91d51ac63252fb7</value>
      <webElementGuid>f39ebf3e-b651-4882-b1ef-c5d3d74d8465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>89a44007-4ade-440c-a4cf-ecc75b0c9f4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>3ab4d051-3dc0-41b8-85df-1ada8c8c3eb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b4-l2-28_2-l2-46_6-b2-b2-TextArea_Answer']</value>
      <webElementGuid>0d6f99a3-2508-4679-93ba-e222240ac317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
