<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-xejf40pdhmi6</name>
   <tag></tag>
   <elementGuidId>38826e04-37e7-4881-a32e-b7dcf01faac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-xejf40pdhmi6&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-xejf40pdhmi6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9ce63c30-89d2-400a-b66c-5eb3a19f8742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>f313064b-f972-453d-bc4b-3aa03fcbb526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>229f5b5e-f693-4a44-887f-8d9917315c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>e401a433-ecf5-4230-88c7-47a3ad1f0ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6ab34693-9e51-4ad1-a3db-6a59c73fceb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-xejf40pdhmi6</value>
      <webElementGuid>e462bc3a-dc31-433d-be24-6e56d9d92943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fa3321db-f1f6-471b-87b8-6fe0a78f4579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>310d0ef4-5260-45d0-8933-4d329ad4e146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>a452877e-05b4-4c8c-935c-4bf400f17b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LejsyssAAAAACso91LtjLm2nx0fjqQkozzt3RVt&amp;co=aHR0cHM6Ly9zYWt0aS1zYW5kYm94LmNzdWxmaW5hbmNlLmNvbTo0NDM.&amp;hl=en&amp;v=jdMmXeCQEkPbnFDy9T04NbgJ&amp;theme=dark&amp;size=normal&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=ul5dqw3wezhc</value>
      <webElementGuid>9f7362ec-8e39-4fc1-a0ca-618e0c8c26f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b1-b1-ContainerCheckbox&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>7a929f70-050c-442e-95c2-6ca4c4db5b13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-xejf40pdhmi6']</value>
      <webElementGuid>dbd5eff6-f064-42f0-b9cb-01343a296736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b1-b1-ContainerCheckbox']/div/div/iframe</value>
      <webElementGuid>82aed725-74f9-43b9-9c4b-b29e83f318b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a29e1982-3a90-4146-bf0c-62c661df8b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-xejf40pdhmi6' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LejsyssAAAAACso91LtjLm2nx0fjqQkozzt3RVt&amp;co=aHR0cHM6Ly9zYWt0aS1zYW5kYm94LmNzdWxmaW5hbmNlLmNvbTo0NDM.&amp;hl=en&amp;v=jdMmXeCQEkPbnFDy9T04NbgJ&amp;theme=dark&amp;size=normal&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=ul5dqw3wezhc']</value>
      <webElementGuid>0feb1f7f-8466-4283-b500-60a9144250ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
