<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Password_a-svcu6vlwg147</name>
   <tag></tag>
   <elementGuidId>06619021-0a2e-4902-968e-78d224376890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-svcu6vlwg147&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-svcu6vlwg147']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b6247cdc-f702-407d-b74f-6a78dce1d8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>c04c2139-c98a-4c51-a77a-dbc2d7b48c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>8a74fe68-b690-4288-a553-087495921e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>ae038d03-f5a6-43f1-a69e-663aca4d63b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>eab66960-aef9-4350-82e4-1a473da78f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-svcu6vlwg147</value>
      <webElementGuid>97508e84-6601-47e8-94e1-d6fa0f2ba918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d527316-6bf5-41e1-a438-0e867f5ecf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>30517f0e-8ee2-4e2d-85a3-2b2658fe84b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>7f149e3e-4b66-4e41-b760-21d3d5e37896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LejsyssAAAAACso91LtjLm2nx0fjqQkozzt3RVt&amp;co=aHR0cHM6Ly9zYWt0aS1zYW5kYm94LmNzdWxmaW5hbmNlLmNvbTo0NDM.&amp;hl=en&amp;v=jdMmXeCQEkPbnFDy9T04NbgJ&amp;theme=dark&amp;size=normal&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=iicqdmh09c2k</value>
      <webElementGuid>0ae8d0d5-5eed-4582-87d4-cf9213dc15cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-b1-b1-ContainerCheckbox&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>7cb42176-6831-4e6b-ae12-b1a000e10fd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-svcu6vlwg147']</value>
      <webElementGuid>a9d56ff5-2581-4cfc-a56d-fb22668b1373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-b1-b1-ContainerCheckbox']/div/div/iframe</value>
      <webElementGuid>02ccf2c9-51bf-4b8d-a582-246213a269f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>90652702-4f12-463b-93fc-e83ffb932d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-svcu6vlwg147' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LejsyssAAAAACso91LtjLm2nx0fjqQkozzt3RVt&amp;co=aHR0cHM6Ly9zYWt0aS1zYW5kYm94LmNzdWxmaW5hbmNlLmNvbTo0NDM.&amp;hl=en&amp;v=jdMmXeCQEkPbnFDy9T04NbgJ&amp;theme=dark&amp;size=normal&amp;anchor-ms=20000&amp;execute-ms=15000&amp;cb=iicqdmh09c2k']</value>
      <webElementGuid>1fc3a2aa-30c5-48b4-b317-b205cb2fc02f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
