<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__EndDate</name>
   <tag></tag>
   <elementGuidId>bebffee3-221f-49ca-b9e6-4dfe3a765a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b1-b1-Input_StartDate2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b1-Input_StartDate2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31649c9d-4ff2-4f9e-b4e7-2dd6ad959ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b4b1cc2c-0127-44f7-b32f-8ae263fca8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>95235d78-84b9-4d97-b88b-d01b459a972f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e51b3251-a240-48f6-93ff-5389eb8995a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-08</value>
      <webElementGuid>a211ac2d-3d6e-4f3d-b8c7-c543f03a39d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2022-03-31</value>
      <webElementGuid>6a214d5f-beca-4577-a021-1311942502c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-Input_StartDate2</value>
      <webElementGuid>b7a62231-1f03-4df1-b7cf-8859ce7f4c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b1-Input_StartDate2&quot;)</value>
      <webElementGuid>fe3b5838-289f-4a8f-8e60-c9d9e5b4d57f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b1-Input_StartDate2']</value>
      <webElementGuid>7cd34896-0f34-4bcd-b20f-4df3f5010fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-$b1']/div/div/div[2]/span[2]/input</value>
      <webElementGuid>7efaf667-c8bb-4b67-a0b6-b3a78dae8fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>f9ece361-7af3-4147-ad50-71e86c3ff81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate2']</value>
      <webElementGuid>1241966d-092d-40ce-abd7-26aa74cf622f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
