<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartDate</name>
   <tag></tag>
   <elementGuidId>f719309d-4367-4bb9-9ba0-f1b6e1c251fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b1-b1-Input_StartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b1-Input_StartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dd5526b-58b1-4d7e-b831-3fd9227c3a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>270dc3bc-6fb7-40f1-a04d-3d22e0625549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>22c65b6d-1c82-4c9c-b1c5-d1df352edad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cc44fbac-7796-4eb5-9ae2-8b1ecc3d36f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-08</value>
      <webElementGuid>7b038c26-f1cf-43bf-9dd2-f9d72ee99ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-01-01</value>
      <webElementGuid>89122749-ef9b-46f3-920e-114b95fadad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-Input_StartDate</value>
      <webElementGuid>f5e37a1c-8a07-4f6e-a1c0-0399377f150c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b1-Input_StartDate&quot;)</value>
      <webElementGuid>2dfc4e4e-d732-4604-ad8b-20b3debb6ae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b1-Input_StartDate']</value>
      <webElementGuid>d309108d-e986-40f0-8a0d-a780749526e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-$b1']/div/div/div[2]/span/input</value>
      <webElementGuid>863c45e3-13c8-420c-a75e-45491bb2eecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>ea83af69-d524-4fc7-9fe9-6ec1018696ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate']</value>
      <webElementGuid>81daebfe-90b0-4931-a184-aa2b01d9d97d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
