<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_b3-b2-Status2</name>
   <tag></tag>
   <elementGuidId>5a8913c8-cabb-4f06-8935-e262eb9909e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[required=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@required = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a0b6b4b5-f2a9-4eea-acd4-50d46956e625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>fd24437e-5926-4887-9ba9-9be85e04bd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6782e55b-d859-4ed5-8829-262848d4333c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-Status2</value>
      <webElementGuid>2cd1e123-9cad-4d2a-8d14-1da8439fbaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select statusDisetujuiDikembalikan</value>
      <webElementGuid>960aaa7f-dbdd-4b56-a9fc-fdc5fbbe9566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3ffeb2016fcabd641620f8d9ac09c4c1</value>
      <webElementGuid>b56aed24-2e21-4d1b-b33c-dddb8557aee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@required = '']</value>
      <webElementGuid>97ff24d8-8df8-4a2d-b95e-05aebc25dbbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@required = '']</value>
      <webElementGuid>f5380de9-df5a-48f5-94df-891a48c8a722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-Status2' and (text() = 'Select statusDisetujuiDikembalikan' or . = 'Select statusDisetujuiDikembalikan')]</value>
      <webElementGuid>740bdbcf-ed25-4247-ac07-e2f86c3bca1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
