<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_b3-b2-TextArea_Catatan</name>
   <tag></tag>
   <elementGuidId>8fdb2e74-6f8d-4ba4-97e9-928854cd0d9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-textarea=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-textarea = '']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>19610929-b2b5-4ec0-b52a-5daecdcef58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>b0a53662-5c3b-468d-ae62-2f4bc1221f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>539c49b3-67e5-4980-9a48-7564dc1f3aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>74e72f8d-e7db-4caf-9399-dfa79f0bc663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-TextArea_Catatan</value>
      <webElementGuid>2794bb69-5164-42dc-b50d-6b3e8af17938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0983327a1988361bf91d51ac63252fb7</value>
      <webElementGuid>effad085-95a4-40e0-91ef-9d5ef4503318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>213b36b4-aa4d-4825-b7e1-3ccca14dda69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>2ef56a76-130f-49fb-8bd6-b8df924fd783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b2-TextArea_Catatan']</value>
      <webElementGuid>c921a22a-c793-4515-addf-74a192ee5af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
