<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Survey</name>
   <tag></tag>
   <elementGuidId>d65fa0b4-61d6-4f37-a409-efcde9f2ac28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-custom.btn-custom--btn-vividorange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[1]/div/div/div/div/div/div[11]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b3d0b3e-26a2-445b-8dca-1944a6443248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-custom btn-custom--btn-vividorange</value>
      <webElementGuid>6447b503-317b-402d-9414-7a2b3a7a9d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>de51da1c-89c8-467d-9b8b-a44854406ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Survey</value>
      <webElementGuid>85057a43-2395-4a18-9670-3a796d55594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;$b6&quot;)/div[@class=&quot;padding-base&quot;]/div[@class=&quot;margin-top-base text-align-right&quot;]/button[@class=&quot;btn btn-custom btn-custom--btn-vividorange&quot;]</value>
      <webElementGuid>9f462424-37aa-44b8-b8f2-bcf1c9ae9de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>7d8cfbac-6841-4a3d-88cf-50ee72feca67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b6']/div/div[11]/button</value>
      <webElementGuid>42910a5a-f424-4932-b0ff-5533405b494d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Document'])[1]/following::button[1]</value>
      <webElementGuid>d78699e1-bc8a-408b-9d6d-f3cf3faad11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketidak Sesuaian Dokumen'])[1]/following::button[2]</value>
      <webElementGuid>4db685ed-76a1-474b-9609-a0bc39d64eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>d46152db-0a13-4aa1-8cb8-3f60e19b3489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Survey' or . = 'Survey')]</value>
      <webElementGuid>e35e1b95-6965-4327-9379-6d0e37cf7f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
