<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b2-l1-17_8-b4-l1-26_4-b1-SubMenuHeader</name>
   <tag></tag>
   <elementGuidId>f4f21929-bffb-42a3-9020-6978429fc4ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[2]/div/div/div[1]/div/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.su85q3aji6d&quot;] .osui-submenu__header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49822ff9-c71f-4f7c-ae06-5eced1b2e8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>f2947cf8-4147-4d82-87cf-4c896b8f0aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_8-b4-l1-26_4-b1-SubMenuHeader</value>
      <webElementGuid>eeac3f17-333c-4f28-a87e-87923130d6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fac6aa4-3778-42a8-a7d6-ed1dbce02c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e153aa6-036b-496c-aadd-f82d8ce4b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_8-b4-l1-26_4-b1-Items</value>
      <webElementGuid>043c6c52-ac60-4555-913d-d695f4ef01e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>0b9d982f-93a9-425b-9d4e-c28de5a9f10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55ce7f68-aba9-4e54-9feb-3f614c0e50eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akuisisi</value>
      <webElementGuid>1378df60-0304-44d5-a81f-4cc3e8789bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8e441294133c39324a15df5e274e90f4</value>
      <webElementGuid>f2107c4a-349a-4643-9038-12e00228fa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.su85q3aji6d']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>71abdea8-5241-4b3d-b10e-3bf8d5cd51a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.su85q3aji6d']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>e3b25f28-2992-42d1-aab8-c61120855d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_8-b4-l1-26_4-b1-SubMenuHeader' and (text() = 'Akuisisi' or . = 'Akuisisi')]</value>
      <webElementGuid>a7859bc5-3737-426c-a3e1-8359c6df00e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
