<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b2-l1-17_8-b3-SubMenuHeader</name>
   <tag></tag>
   <elementGuidId>4af8d913-0921-4257-a0b1-068269906a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[2]/div/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.ap63un39ttu&quot;] > .osui-submenu__header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c439af1c-eaf0-40f3-9b0f-8a79ed91cd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>9527dc2d-f716-47dd-95c1-64ef0194ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_8-b3-SubMenuHeader</value>
      <webElementGuid>688f635e-1590-41e4-b00c-612ce5c1268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa8c1a94-435a-4c68-98d8-176428c63c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64c71263-4696-4447-85ba-ba4e5252437f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_8-b3-Items</value>
      <webElementGuid>873461e8-5129-4706-afaf-22cd9315a7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>f077eb60-c5aa-4398-9084-210f00e8b0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>95550128-65be-4eef-ad88-e7d06871f910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monitoring &amp; Review</value>
      <webElementGuid>3152a6de-993d-46c7-997e-cf9c433bfdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8b401dfcb776c41b4623eb0360e3a36c</value>
      <webElementGuid>de7fc3da-9025-4e95-994a-ad290d19527f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.ap63un39ttu']/*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>d982f685-c882-41d5-b84b-35e3b37c6321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.ap63un39ttu']/*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>22fa38b4-3e91-4335-b6f8-aca7904ab0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_8-b3-SubMenuHeader' and (text() = 'Monitoring &amp; Review' or . = 'Monitoring &amp; Review')]</value>
      <webElementGuid>d544b126-3402-413a-b98f-06cb85250881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
