<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_b2-l1-17_10-b4-l1-44_4-b1-SubMenuHeader</name>
   <tag></tag>
   <elementGuidId>752b5b1d-6948-48db-944e-67546be9ca75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/aside/div/div/nav/div[2]/div/div/div/div[4]/div/div/div[2]/div/div/div[1]/div/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;\30 \.u28zmxgnoj&quot;] .osui-submenu__header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d411a4f0-4b51-47fa-845d-fab586cece66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>osui-submenu__header needsclick</value>
      <webElementGuid>9c588726-31e4-437e-a470-0442a91e9d74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b2-l1-17_10-b4-l1-44_4-b1-SubMenuHeader</value>
      <webElementGuid>a096e59a-7c78-4b29-b139-b266fc734982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61e627ca-6ef4-40be-a4c9-75f3d36c5228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>da18eb7d-718a-4365-81ad-f3cb65796494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>b2-l1-17_10-b4-l1-44_4-b1-Items</value>
      <webElementGuid>1ccbb26d-0b56-44e1-bef2-ae5e1e23fca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>b055972f-a996-4ab9-8903-eb0017c7a780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>428eea7d-f761-49c8-ba82-4b8785bfcbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akuisisi</value>
      <webElementGuid>a2fc6a42-cd57-4c67-a609-82af3411d599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6451e6bba5ba101f0a892dd699328d1d</value>
      <webElementGuid>c5af7122-f067-4d7d-8d55-2476bbdf6524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '0.u28zmxgnoj']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>00301ec8-e5f4-4dea-aecb-abb9fd7fd21e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '0.u28zmxgnoj']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' osui-submenu__header ')]</value>
      <webElementGuid>e13a1f1d-fb6c-400b-ab7e-f4d4876d29b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b2-l1-17_10-b4-l1-44_4-b1-SubMenuHeader' and (text() = 'Akuisisi' or . = 'Akuisisi')]</value>
      <webElementGuid>9ee0dee4-5f4b-44b2-a09a-78e03067f54f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
