<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EndDate</name>
   <tag></tag>
   <elementGuidId>8771d9ea-0728-4b88-be9d-c10577cb54a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-required=&quot;true&quot;][type=&quot;date&quot;][required=&quot;&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d838f58-493c-4ca0-8a81-0cdecb2db1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>79c1e90c-f9e5-4204-a794-947a8d0ec920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>64e89d33-fb2c-444b-97b3-7a26ff00d1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1e092f58-99e5-467d-8874-41b1a56dd64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-10</value>
      <webElementGuid>7d3f7669-1ec7-48e2-a342-b936b1e13bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Input_StartDate4</value>
      <webElementGuid>4b4c8b8b-2d69-4d28-bc27-d7e9f3cf3964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-00e44eaaf6e7f77b842d90dfbfac066c</value>
      <webElementGuid>16c279dd-f513-4284-b8ab-3091f8a93d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      <webElementGuid>30645a28-cfc2-4bed-bd4b-9ab00e10ca2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      <webElementGuid>96b56c39-a5b6-49e6-811b-df144a1de0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-Input_StartDate4']</value>
      <webElementGuid>115cde9c-7d2d-4137-a393-d70c3a4f31d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
