<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unggah</name>
   <tag></tag>
   <elementGuidId>581f71e2-fa03-4051-8680-5902052a4804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-block=&quot;ComponentQuestion\.Item_UploadDocument&quot;] .OSInline.camera-absolute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[2]/div/div[2]/div/div/div[8]/div/form/div/div/div[1]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bcbb159d-cf9a-4a81-9df6-67b33d46892d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>camera1 camera-absolute OSInline</value>
      <webElementGuid>158a65b0-6834-47fe-89b3-ef4a7527feb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah</value>
      <webElementGuid>99b56954-5c58-41bc-ad37-ca94ef1fbfaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e1153ddd17b44018b72fc421f123a773</value>
      <webElementGuid>3bfab8d8-215a-4afd-86a9-bd8e125a267c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-block = 'ComponentQuestion.Item_UploadDocument']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' OSInline ') and contains(concat(' ', normalize-space(@class), ' '), ' camera-absolute ')]</value>
      <webElementGuid>38757b91-4d5b-48f2-8028-0e394c04a26d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-block = 'ComponentQuestion.Item_UploadDocument']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' OSInline ') and contains(concat(' ', normalize-space(@class), ' '), ' camera-absolute ')]</value>
      <webElementGuid>77848190-451e-4a0c-b1cd-179e05b36641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Unggah' or . = 'Unggah')]</value>
      <webElementGuid>3481a43f-fe06-4fd8-9632-8bb43c3eb1e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
