<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_1</name>
   <tag></tag>
   <elementGuidId>5f0aa58b-414e-493f-87c2-a55480bd6fcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[1]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa1fecd2-064c-4c51-ab7d-6d0d4f330a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>cfb70ca6-2397-4c66-8f50-8b370efbd55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioButton1-input</value>
      <webElementGuid>52892ab4-bd5a-4cec-9108-750ce8df54a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>683022df-0e89-4819-bed1-81eb79a00ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1</value>
      <webElementGuid>d7e4f6d4-66f8-43b9-9c44-b45dc2a769fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>460d3f76-8d38-42d1-a767-c75e2a8691ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-88cf90d504e199cad6e9aaee009cf308</value>
      <webElementGuid>ae657eea-5e80-484c-8746-6895c7fe3a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>6fb2a368-e69a-49c0-8b72-3c5d5028119b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>042d63eb-fdad-478b-a7d2-6212ba196863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>34178bf6-8239-4b44-b0de-728bc2ac7a61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
