<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai_1</name>
   <tag></tag>
   <elementGuidId>96e9ba12-dc4a-4c60-9cee-11563b9043f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[2]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e426a3b-e740-4ec3-8a75-3629a675f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>92150b8c-109b-46d8-a243-c1e45dca342d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioButton1-input</value>
      <webElementGuid>2caceef0-9d85-4086-9538-aa20d44924cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>3bc33522-e7d4-43c7-9f93-e10e725d6069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1</value>
      <webElementGuid>a8c83205-b375-45b1-a840-b6bd258ca56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>4420257d-0914-477c-b5fb-7e560180b892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-33d266ccbbd2a5f5daab4818f3eab42c</value>
      <webElementGuid>5ac98602-9438-4c7b-92e6-de9b7b5ffcbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>77311173-256b-4e2d-b580-05e9704ea707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>a422f915-0048-4c34-9960-1104f8d047bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioButton1-input' and @name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>43809a40-8830-40a5-a8f1-74ddbd2ab3ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
