<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_2</name>
   <tag></tag>
   <elementGuidId>22504e8c-0449-4356-aa77-1cbe3452986c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[3]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03c364ea-992b-4036-9eb3-d318166dd76c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>32cf1c4a-d92a-47bb-9073-4864e6820d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioButton1-input</value>
      <webElementGuid>3bd34c6f-610e-4e6d-b450-e002750269b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>87ac9eaa-c2d8-4a45-baf9-aa7462e38003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1</value>
      <webElementGuid>dea3abe7-286b-4017-a8a5-35b90e364e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>4d3ec724-7157-4769-9058-bac5ac8288cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c11746fe39354b7b2c9eb89c1d1770de</value>
      <webElementGuid>1839f210-0668-4aa3-b093-05029b64d269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>9a20fb23-9ac7-4aa1-a234-94436827f8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>8b05f384-3c33-4c33-beef-21d072aa11c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>727ad13f-f219-47d7-a56a-f25b3e178c2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
