<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai_2</name>
   <tag></tag>
   <elementGuidId>9d29a9f9-c596-4176-bc59-6cf99b728f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[4]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0a672c3-615c-4755-ba29-b5b5194a868f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c52ada1f-5d34-41df-800f-30e0530a6bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioButton1-input</value>
      <webElementGuid>98a489a5-3956-4553-a283-2d4888c13b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>1b323528-fece-484f-9ad0-309b6332a821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1</value>
      <webElementGuid>f3ba9faa-7a7c-46a8-828a-3f6d34e1f2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>0b3eb78e-103a-48ed-bfac-992a85843686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd384fd5edabb6652107d24075a188d3</value>
      <webElementGuid>a66da54d-d0e1-4757-80ce-f7b213546e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>5b67e8a5-0aa8-40a0-8df6-36145955e039</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>fd7aa193-8345-4d73-ab04-faf4c43b9951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>045479f2-df9c-4866-9eef-ce5a159d9404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
