<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Kategori Temuan</name>
   <tag></tag>
   <elementGuidId>a137e5c2-e8cd-4a26-9cd2-3f101aa47bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.dropdown-display</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[2]/div/div[2]/div/div/div[9]/div/form/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16c89123-abe2-4a3d-a0b8-4828d4cba4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>8afe59f7-117b-4f46-b393-3d815a6660e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50ca6abd-c485-4784-8703-52d77ba5aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-29_1-l2-36_8-b2-b5-Dropdown1</value>
      <webElementGuid>f27ed6e3-0b77-4141-8cad-05ef607f4914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select OptionRendahSedangTinggi</value>
      <webElementGuid>82fecd1c-330b-4c3f-a300-bd6c307b8266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-968359a9b6f8cbd1c0f7d51d9b6b9d65</value>
      <webElementGuid>439ce056-acde-4b80-bf58-5d9c88092ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dropdown-display ')]</value>
      <webElementGuid>665c8cbf-c095-4c7f-986e-3097ce7a212f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' dropdown-display ')]</value>
      <webElementGuid>c6b9321d-bb6b-481d-8c60-a0d4b66d9324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-l2-29_1-l2-36_8-b2-b5-Dropdown1' and (text() = 'Select OptionRendahSedangTinggi' or . = 'Select OptionRendahSedangTinggi')]</value>
      <webElementGuid>e6295f5b-9af7-4a08-9e7c-0919796d2112</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
