<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Hasil Pemeriksaan RCU</name>
   <tag></tag>
   <elementGuidId>7399506f-4901-40cb-bdba-e15cca10e78d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-textarea=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[2]/div/div[2]/div/div/div[7]/div/form/div/div/span/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>007386f5-815f-4b1f-bb67-249d1a80e5a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>82cd8ba3-82a3-4f09-aabd-6c839eeed6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>aaa77536-a48f-484a-abff-a234990e91af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength_input</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>132f58d2-2792-47bc-aaa7-8d86954a4dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>50ec4ab4-a7bf-4b8a-8770-e4d9985e1e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-29_1-l2-36_6-b2-b2-TextArea_Answer</value>
      <webElementGuid>23d74ce2-ab3e-4089-9536-d08ffa36cfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0983327a1988361bf91d51ac63252fb7</value>
      <webElementGuid>8741d3af-cf89-4572-b567-5839f7143edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>dedb8c20-c215-4c54-b301-693626f1f565</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-textarea = '']</value>
      <webElementGuid>6dbb8230-7d0d-490a-af7b-0180311eb28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-l2-29_1-l2-36_6-b2-b2-TextArea_Answer']</value>
      <webElementGuid>5670e21f-b333-4be3-b001-2dd49f82ae9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
