<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lihat Dokumen</name>
   <tag></tag>
   <elementGuidId>4b31adbf-e0eb-44b3-a36e-013aa4bb10f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div[3]/div/div/div[2]/form/div/div/div[2]/div[3]/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-darkgreen.full-width</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b33b0097-25aa-46e1-bdf3-442f2f03d98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkgreen full-width</value>
      <webElementGuid>40cf459a-868c-4453-8641-c5036f8ca886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>db1ef154-a8cd-4f41-9d17-f06da185bc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Dokumen</value>
      <webElementGuid>de24e567-4953-42e8-9542-ab9baac3395c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-l4-291_0-b2-b8-Column2&quot;)/button[@class=&quot;btn btn-darkgreen full-width&quot;]</value>
      <webElementGuid>5f8bf48d-024e-4b2d-86c5-a41c924d5f49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>aa3dffad-97ed-4b54-8c75-f7d1042cfd4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-l4-291_0-b2-b8-Column2']/button</value>
      <webElementGuid>223fcb74-9b27-4e9f-850c-d41e6e2ef070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Tindak Lanjut'])[1]/following::button[1]</value>
      <webElementGuid>d107cd0b-e9fb-4cb8-8ab7-ab05648a2943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenggat Waktu Penyelesaian :'])[1]/following::button[1]</value>
      <webElementGuid>b3aa0489-8284-4e14-a443-a6b3900822e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Tindak Lanjut'])[1]/preceding::button[1]</value>
      <webElementGuid>cb2cfe25-e9f4-441e-9202-58f867466a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>5d62a909-c527-4981-92bf-172b40f2f457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Lihat Dokumen' or . = 'Lihat Dokumen')]</value>
      <webElementGuid>895873aa-44a0-4b02-8076-0faaab2d5166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
