<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Catatan_TindakLanjut</name>
   <tag></tag>
   <elementGuidId>560c63c8-ec81-404f-ad61-e1ed8aec5262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div/div[3]/div/div/div[3]/div[2]/form/div/div/div[2]/div/div/div[2]/span/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-l4-291_0-b2-TindakLanjutCatatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>69ad0cac-ed08-4bad-bd49-c526d67ac719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-area-custom OSFillParent</value>
      <webElementGuid>8dcc61ea-e247-41df-baeb-75f05e9d829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>1cd9eabd-ff8a-4310-a790-4d2de1f63b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>154555ac-5e14-4429-9490-9c9986e51258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-l4-291_0-b2-TindakLanjutCatatan</value>
      <webElementGuid>cdef84c9-e7c6-4ef2-98ce-173f1ce19f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-l4-291_0-b2-TindakLanjutCatatan&quot;)</value>
      <webElementGuid>7add1e91-e8d3-4ea3-91d7-f9ef9ef2076a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='b3-b2-l4-291_0-b2-TindakLanjutCatatan']</value>
      <webElementGuid>890d0d56-b09c-444d-af46-62c92b6cacbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-l4-291_0-b2-b12-Column2']/span/textarea</value>
      <webElementGuid>15a47b66-7125-4dcb-8309-3beac9176230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/textarea</value>
      <webElementGuid>3e1f0eaa-5f32-4077-b058-45e9c5f0f7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'b3-b2-l4-291_0-b2-TindakLanjutCatatan']</value>
      <webElementGuid>af9aa910-3487-42c9-9710-7c23504e95ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
