<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b1-TanggatWaktuValue</name>
   <tag></tag>
   <elementGuidId>ea0124af-c549-409f-8550-a80953d10809</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-required = 'true']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-required=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a1b5fa4-f63e-4d38-9a1f-b65e93409f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ThemeGrid_Width4</value>
      <webElementGuid>8c8a5bca-4f60-441a-99d7-c9085f3fe968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c0e1b1c9-709c-4593-8544-267ae3c24d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff4479cf-3fef-4f50-87e0-eb5950e8d5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2026-07-15</value>
      <webElementGuid>7b14c464-0df6-448b-94a3-7e5ea077eacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-TanggatWaktuValue</value>
      <webElementGuid>6ce7d544-e0ea-42a3-8236-1ba9f02ef801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-636059f55691eb6b6fd3db9ed640e633</value>
      <webElementGuid>2d20a6e4-1f3f-4e69-b7e1-06c3261c2712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-required = 'true']</value>
      <webElementGuid>55d57a51-8445-492e-80c7-b4e010fd80f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-required = 'true']</value>
      <webElementGuid>9d2cd261-853e-4298-b863-196daf095c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-TanggatWaktuValue']</value>
      <webElementGuid>2f177c7a-4cdc-451b-94e9-4f5b8d3c09e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
