<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartDate</name>
   <tag></tag>
   <elementGuidId>45c99a09-a798-4e0f-89e2-b1214ad4f229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.input-date:nth-child(1) [type=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/div/div/div/div/div/div/div[3]/div/div[1]/div/div/div[1]/div[2]/span[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>349d06d2-4eb8-4792-8054-2577fd1c042f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c589e25a-ebab-4139-abc0-eeec4d919fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>4c75553e-e45e-406b-8d38-48eaeb22269a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a9f76c7c-0f3c-4df6-8a0d-a4bb08d496ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-09</value>
      <webElementGuid>c273a5de-a3b6-4ddf-a13b-1fd439033f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-Input_StartDate</value>
      <webElementGuid>00ad3439-851d-46e9-a18d-5f3e381312e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-94d2019b4225b0243156f728b2a62f08</value>
      <webElementGuid>1374c4a9-2543-406a-8ddf-4a83d0bd5a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@type = 'date']</value>
      <webElementGuid>660b9dba-ca38-4c9c-9821-226beba5a2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' input-date ') and (position() = 1)]//*[@type = 'date']</value>
      <webElementGuid>ae757d5e-ee23-4205-96d7-14ba19b572e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-Input_StartDate']</value>
      <webElementGuid>9fe2b07e-8060-4d2e-a18a-729d04ebf0f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
