<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JenisSearch_ByTask ID</name>
   <tag></tag>
   <elementGuidId>505cc1a2-2268-4c09-ac61-c02db5009627</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b3-b2-b1-Dropdown6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b3-b2-b1-Dropdown6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bcc223b2-fcc7-4d00-acfe-9e4b80f5f701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display dropdown</value>
      <webElementGuid>abb6b4c3-b85d-428b-9cae-786f80eafd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ceb26075-f51d-4a55-a9eb-647ecb6f4aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Dropdown6</value>
      <webElementGuid>a80bfb06-893e-44cf-8a31-f63160fc224d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search ByTask IDJenis SupplierKategori SupplierNama SupplierTipe Tugas</value>
      <webElementGuid>e7f9c054-6ae3-42c7-b208-b36c2dec511c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b2-b1-Dropdown6&quot;)</value>
      <webElementGuid>ce8818e0-83b0-459f-bedb-b3b31ee4745b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b3-b2-b1-Dropdown6']</value>
      <webElementGuid>f0304673-8f4f-40b6-ba4b-e90878c09161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b2-b1-Dropdown6-container']/select</value>
      <webElementGuid>70249c8d-235f-40cf-bfeb-82b26522b2c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>2a573d9b-e9d8-422a-9e0e-b075c40e4016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/preceding::select[1]</value>
      <webElementGuid>165162f6-2d7e-4a96-b14d-96b754d96460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task ID'])[2]/preceding::select[1]</value>
      <webElementGuid>6ba25249-1f5d-4a65-a003-494f2838e734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>5130b85e-43ff-4848-8592-c6a3d783ca53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b3-b2-b1-Dropdown6' and (text() = 'Search ByTask IDJenis SupplierKategori SupplierNama SupplierTipe Tugas' or . = 'Search ByTask IDJenis SupplierKategori SupplierNama SupplierTipe Tugas')]</value>
      <webElementGuid>3e2a4282-adde-44a3-b83a-48433d8bdb3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
