<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Draft</name>
   <tag></tag>
   <elementGuidId>ee9bb0c4-5269-46f5-aac4-640d2ec254cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[2]/div[1]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn.btn-custom--btn-amberorange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9d303c3-e21d-41f9-85ca-8dd21d9fa028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-custom btn-custom--btn-amberorange OSFillParent</value>
      <webElementGuid>844fee7d-1465-4dd9-bcf0-7e1e371a0ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1add691f-93be-4cd1-abed-41d16b601dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-ButtonDraft</value>
      <webElementGuid>0dd749b1-47a2-4362-b164-2730cdd1697a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>4daec867-3b00-4342-bd36-5a7b958c2868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6122b38b6624c96f5ffd2b7a811d98fd</value>
      <webElementGuid>dadbf55c-67af-4492-90e0-60917106c606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-custom--btn-amberorange ')]</value>
      <webElementGuid>fdbcccd8-09c5-402c-b23a-87f1efbe8aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' btn-custom--btn-amberorange ')]</value>
      <webElementGuid>98ce0e11-9b06-4b2c-b0b0-74a683cab039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b3-ButtonDraft' and (text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>4e2c7e55-7a98-4d9b-a07a-bf4c20732763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
