<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_1</name>
   <tag></tag>
   <elementGuidId>888fbefd-c30c-4268-8c00-02215a13a81a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[1]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2218ca36-a2df-48db-b706-b29c386cd730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>aca88916-0739-4279-b610-e170bfc71042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioButton1-input</value>
      <webElementGuid>f68c0768-5ca6-4a96-8c75-93af5e69cd9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>b83c88d0-0cda-4654-9ce0-f71641e6ecfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1</value>
      <webElementGuid>40806e21-3a14-4e71-9851-145dda3f509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>f57652ce-162b-4a10-969a-6b774da4fed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-88cf90d504e199cad6e9aaee009cf308</value>
      <webElementGuid>a706ecb0-4ba1-4bc9-badc-c4d97ad222d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>ddbc0905-e486-4398-b4a8-dd3f5527fa5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>b9505be0-7b75-41a1-a2a4-a9da32c69fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_0-RadioGroup1']</value>
      <webElementGuid>6a31edf8-77bc-465d-94b4-b48535e017d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
