<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Sumber Informasi 3 __1</name>
   <tag></tag>
   <elementGuidId>cb90f8f1-67b4-4bf8-bc51-87c2b5b8ca1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[2]/div/div[2]/div/div/div[5]/div/form/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;MIN&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>823738a6-0969-4aab-a41d-1f15a5f58115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>5b65a2f9-c93b-4079-baef-e01231fddc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e66dc02-e302-4cb1-8768-956fa11469ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc372c49-5224-4732-b253-50b10ac1d5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>93e658c4-6e57-43dc-9447-5af2e6b77f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>MIN</value>
      <webElementGuid>b1408e00-879b-4eab-a8c7-d752c42df54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-29_1-l2-36_16-b2-b1-Input_QuestionAnswerValue</value>
      <webElementGuid>4edf1693-7946-40d3-bfe3-e5b65caf75e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bcfda39c549e506454a4c0d2e8ceeb4b</value>
      <webElementGuid>df60a435-026e-4bbc-a063-f1875b3f982e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'MIN']</value>
      <webElementGuid>7e545a8e-2aba-45a8-9096-3ae68e2dbc41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'MIN']</value>
      <webElementGuid>a12ba9e7-79c2-4278-a3c1-7efad3095c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b3-l2-29_1-l2-36_16-b2-b1-Input_QuestionAnswerValue']</value>
      <webElementGuid>6cd9a901-a897-41ed-9745-181d1aac70af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
