<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai_1</name>
   <tag></tag>
   <elementGuidId>626e6a19-4bed-49f1-ba91-596733999ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[2]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1589739-8009-487c-94ec-14d29f5519b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f26e6e1-28fd-4cf7-accd-f898356a96cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioButton1-input</value>
      <webElementGuid>43760f66-a7df-4f19-99ec-4236a4e777c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>d5df581a-5163-41ec-90f7-6ce3c711076f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1</value>
      <webElementGuid>67ba6f4c-aae4-425b-8294-4a3cd41901f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>bf883126-ab60-4e22-bbb1-d388688bfe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-33d266ccbbd2a5f5daab4818f3eab42c</value>
      <webElementGuid>7846610f-ef95-42c5-af8f-66e1691ce134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>26bbe0e3-d06d-48f9-a67f-2bff0b32ce74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>0eb89fab-ca3e-4be5-a380-161cf70b06b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioButton1-input' and @name = 'b3-l2-29_0-l2-30_6-b2-b8-b3-l1-54_1-RadioGroup1']</value>
      <webElementGuid>6499090e-af23-44c9-a692-a3d6499c2cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
