<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tidak Sesuai_2</name>
   <tag></tag>
   <elementGuidId>74532d76-4cb6-46ac-9f54-01cf988317f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[4]/div/form/div/div/div[3]/div/div/div/div[2]/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a23f382-7add-4bef-9935-7615558ea039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>88b1fb94-6233-4162-ae8c-0691fb82eddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioButton1-input</value>
      <webElementGuid>d23c4170-f3f1-4923-90d2-59e3d506735d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>bbd0b31a-1262-428b-b058-81942d1ff7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1</value>
      <webElementGuid>a9045e28-bebd-4867-a117-763a605ab5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tidak Sesuai</value>
      <webElementGuid>733efe6a-fef1-4dd1-8e8b-53300667d6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd384fd5edabb6652107d24075a188d3</value>
      <webElementGuid>a690e628-2c5f-4b5f-9f3f-5c14b750c53b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>7f1f0286-1918-4de1-a882-912bc0c01a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>f9a923e7-a962-42f5-8f37-e072eb5c818d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_7-b2-b8-b3-l1-59_1-RadioGroup1']</value>
      <webElementGuid>1c9a994c-ffe4-4963-b15d-ec205a20f4ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
