<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesuai_2</name>
   <tag></tag>
   <elementGuidId>1aeabdf8-1fdc-44cb-a70f-f5edb499b9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/form/div[1]/div[1]/div/div[2]/div/div/div[3]/div/form/div/div/div[3]/div/div/div/div[1]/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>967a5880-719d-4190-9e91-4580e00e9af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2ee1bc8d-422a-4eb0-9155-5ea55ff9ccdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioButton1-input</value>
      <webElementGuid>87a4d593-fa7d-4858-8aec-584b259b8e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>5490704b-9af8-4c7f-abe8-0754b172dc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1</value>
      <webElementGuid>d18059a9-b702-41be-b776-89f4cc8bfdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sesuai</value>
      <webElementGuid>a4ce14d3-976f-4344-8eac-6cdded77bd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c11746fe39354b7b2c9eb89c1d1770de</value>
      <webElementGuid>ca4a11c5-9cea-4b0b-8a17-750242342fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>39127348-97e2-48bc-b838-3ad8265195a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>b6a5e507-ddfe-4ee9-9570-0b644e21c24d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioButton1-input' and @name = 'b3-l2-32_0-l2-33_6-b2-b8-b3-l1-57_0-RadioGroup1']</value>
      <webElementGuid>a9daf505-9b41-41ce-a663-66c4959307fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
