<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EndDate</name>
   <tag></tag>
   <elementGuidId>4e938b19-6f0c-4dad-ae52-65f0f075c284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-required=&quot;true&quot;][type=&quot;date&quot;][required=&quot;&quot;][value=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e637c29b-56b5-4058-a43a-2fda29bbb421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a882d712-ba73-4230-b12f-cc766d1ef241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>661e9c33-5570-4b92-9eff-9e05a9b64c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>132ccd84-6a9e-4205-b396-4d1d851f871a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2026-07-10</value>
      <webElementGuid>c3f59302-7ff0-4923-a92d-f65ffb0748d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b1-Input_StartDate4</value>
      <webElementGuid>3420602e-ce5b-494f-9c73-6e72925c3b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-00e44eaaf6e7f77b842d90dfbfac066c</value>
      <webElementGuid>75583a44-2f91-4e24-8bce-487ea3fe3455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      <webElementGuid>715897c1-59de-4649-93cb-bfed71baf63e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-required = 'true') and (@type = 'date') and (@required = '') and (@value = '')]</value>
      <webElementGuid>3314f2c7-e8da-447a-ab80-9ecca8162c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b2-b1-Input_StartDate4']</value>
      <webElementGuid>34f2df97-a84f-45dd-bebf-ee4e2982e65a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
