<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaPIC_B</name>
   <tag></tag>
   <elementGuidId>51a0b953-90ea-475e-a840-6daff180f6ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div[1]/div/div[2]/div[1]/div[1]/div/div/div[1]/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;margareta&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17255618-9d2b-4b0a-af10-365b3abba5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>de70ba09-a85a-4026-a901-b9b5ec4cc71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>450c678f-873f-44d1-98e5-262432ea879b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>708dbaae-a2c4-47d4-a575-14b17e0b850e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ff26c9d2-92c9-424b-ac2d-0902bdbcaf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>margareta</value>
      <webElementGuid>1ca3f51b-cbd3-499f-9740-637e3528028a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b2-b5-b2-NamaKaryawan</value>
      <webElementGuid>4a3876b9-2b75-4686-922e-1b2ab49a8df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f7a12b5eae107a0783d5269d7c5c8f7c</value>
      <webElementGuid>7b228b53-7e32-490b-81ec-94b01a6177dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'margareta']</value>
      <webElementGuid>8d96ff41-4ec4-49e5-ae68-ba2762a917d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'margareta']</value>
      <webElementGuid>1ab760a6-7d94-4b87-b49a-1f61829eef73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'b3-b2-b5-b2-NamaKaryawan']</value>
      <webElementGuid>a538d34c-3aaf-43d6-913c-10119bcae794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
