<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-b18-Checkbox2</name>
   <tag></tag>
   <elementGuidId>f3d83777-e1bc-44db-a79f-193777a026ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.columns-item:nth-child(1) .margin-top-s .checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div/div/div/div/div[2]/div/form/div[3]/div[2]/div/div/div[1]/div[2]/div/div/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30703f38-1f11-4f4c-ba68-55eb1c2aac42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8d015c44-8b5c-4344-bc57-1575992007ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c4b4280-8c56-4aa2-ad2d-7632d382987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b18-Checkbox2</value>
      <webElementGuid>1d614aa3-188a-48e3-ba86-06fd16616a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0552f0cdd3839b7d2328500095e8b717</value>
      <webElementGuid>a3e4fda4-7cbd-4676-89ba-b99cf66234cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' columns-item ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' margin-top-s ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>9646309a-77af-4597-9906-6b93c53a4505</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' columns-item ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' margin-top-s ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>e479fcda-785a-4285-a396-1649741765fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-b18-Checkbox2']</value>
      <webElementGuid>67052306-8c30-4fdc-a6c5-b61205551cf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
