<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-Checkbox1</name>
   <tag></tag>
   <elementGuidId>ac0c6a91-161f-4704-a2a2-f62af142ab75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div/div[4]/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0d64ebe-45ae-4243-aa74-873538f50ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7cfc7a58-f2d0-4a5f-a751-ae1f9aa90702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68b56148-03e4-4bfc-8da4-c3299d9d888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Checkbox1</value>
      <webElementGuid>aa5d7d8c-08c1-4397-9cf3-067e6c54f6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b57e2e968320aed890fecfcedd9d539a</value>
      <webElementGuid>c77dc5d6-669d-4fc0-91a2-261c9136f9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>002fa6dc-bb18-44b1-9e9a-322630d07b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>93bd7bd1-cdba-440f-955a-e1288d528952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-Checkbox1']</value>
      <webElementGuid>1c1dfd84-520c-475e-b3a4-9b63b06afc55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
