<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_b3-Checkbox1_1</name>
   <tag></tag>
   <elementGuidId>200d1a30-a1eb-49fd-8b16-1b2b52686457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div/div[4]/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fd48519-77ca-4ee8-9aef-4f18ec77504f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8c540951-2d0c-438e-9442-00ee1782c436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c1f3fd22-36a4-4e7d-83ca-ad35df92332d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-Checkbox1</value>
      <webElementGuid>cfbf1008-0814-4219-bf5a-d0ef7c50f959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b57e2e968320aed890fecfcedd9d539a</value>
      <webElementGuid>c8e658a3-7de2-4d6e-9aab-a9b12a4dee5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>511b675b-bd9c-4786-ba79-f3f20b1f6200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' checkbox ')]</value>
      <webElementGuid>486a05be-b151-4abd-a32a-359f204e44f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'b3-Checkbox1']</value>
      <webElementGuid>c0fe25ed-78cb-4afa-afd3-affe8648aa6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
