<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Status_BARU</name>
   <tag></tag>
   <elementGuidId>d5e19766-c43a-41ba-9e40-ee22014a4a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div/div[1]/div/div[2]/div[1]/div/div/div[6]/div/div/div/div[1]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn.status-new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1ffc8578-0b35-479e-af41-9bf3ee03062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-group status-new</value>
      <webElementGuid>50cb46da-0a43-4bf7-91f9-3b4dee284e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7dce0dc4-015a-4d13-8b1b-97866e0761c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cc673e0-10ac-46cf-9ab6-8942fca8ee6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BARU</value>
      <webElementGuid>3aeeb0c3-ad5b-49af-9c2c-0228bf220a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-05f935ba2a4b579e69f33696710d704c</value>
      <webElementGuid>b5bec77d-8afc-457d-a3b7-6168fc11e866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' status-new ')]</value>
      <webElementGuid>6caff163-4c34-45d0-a21e-7c7424446d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn ') and contains(concat(' ', normalize-space(@class), ' '), ' status-new ')]</value>
      <webElementGuid>98cde550-5949-4f4e-ab0e-97e5e1e60d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'BARU' or . = 'BARU')]</value>
      <webElementGuid>44f29ff1-c527-4ed0-b01a-443e46207fd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
