<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tanggal mulai tidak boleh lebih besar d_26e6d1</name>
   <tag></tag>
   <elementGuidId>f88b4316-742d-40f9-8be5-2b9205258e18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31f158af-1f8b-4529-baf6-ac65eedf895f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message-text</value>
      <webElementGuid>c5607041-b4ec-41bd-b883-465f2a482b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal mulai tidak boleh lebih besar dari tanggal akhir</value>
      <webElementGuid>c7560053-3947-402c-8734-f359f0160f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-error&quot;]/div[@class=&quot;feedback-message-text&quot;]</value>
      <webElementGuid>12e8fff6-c0b2-4a4f-a54c-a9893ea36c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div/div</value>
      <webElementGuid>7db89299-d2ed-4ff7-bcee-a26a8794dbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[4]</value>
      <webElementGuid>93d653a6-587b-434d-a8a2-fec42d604858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring &amp; Review'])[1]/preceding::div[13]</value>
      <webElementGuid>6debd5ec-8bc5-4e3e-84e2-0651b75a16ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tanggal mulai tidak boleh lebih besar dari tanggal akhir']/parent::*</value>
      <webElementGuid>7addd003-b4fb-4766-b5cf-07004d5f59ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>fe19754a-96b7-4326-8ebc-b044b538688d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tanggal mulai tidak boleh lebih besar dari tanggal akhir' or . = 'Tanggal mulai tidak boleh lebih besar dari tanggal akhir')]</value>
      <webElementGuid>8a257f71-cd4e-40f9-8ca5-cd0c969d5116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
