<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Branch Harus Diisi</name>
   <tag></tag>
   <elementGuidId>a3ccb2b7-c337-4e32-bee0-53aeb40d47a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0874145-f040-48bd-9d1e-95bd099384e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message-text</value>
      <webElementGuid>c85a2a2a-9c5a-4e5f-afe6-c4af3b27598e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Branch Harus Diisi</value>
      <webElementGuid>cbd5cbb6-00fa-441e-98ba-340cf221c26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-error&quot;]/div[@class=&quot;feedback-message-text&quot;]</value>
      <webElementGuid>1b0d8582-78ee-4a78-aeb1-3a1f7046eae0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div/div</value>
      <webElementGuid>07507a48-150d-450f-9c6b-16eb7a594800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/preceding::div[4]</value>
      <webElementGuid>615921b1-db60-49c1-b839-77c8c582842a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring &amp; Review'])[1]/preceding::div[13]</value>
      <webElementGuid>a76a04c4-271f-45ab-8e25-6e0aabac7654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Branch Harus Diisi']/parent::*</value>
      <webElementGuid>900b65cb-4a3a-4911-a8b3-d2e5071cf53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>28ba29e3-8b43-4cbb-ae5a-f812db6dc868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Branch Harus Diisi' or . = 'Branch Harus Diisi')]</value>
      <webElementGuid>88d699ae-0fca-4ebf-947e-fdff204e9e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
