<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Registrasi_b3-b1-b1-Input_StartDate</name>
   <tag></tag>
   <elementGuidId>0493ae15-86c0-42f1-9769-3fdbddf38a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b3-b1-b1-Input_StartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b3-b1-b1-Input_StartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8f89365-33c4-4fb5-bdc3-b4322a1f8473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb3283cf-fb0c-4443-a3bd-188a203fa05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>d689803b-4bce-46ca-bc51-de78f92a0a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39a7b7d6-2e4f-49cf-b7b8-72a3dcb5b7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2025-12-15</value>
      <webElementGuid>1b77c5f7-771b-40f1-91c7-ea1c62b14e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2025-12-15</value>
      <webElementGuid>331b7b57-88eb-4d53-85f6-cfd69f464627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-b1-Input_StartDate</value>
      <webElementGuid>e890942e-423f-40a6-b396-16b072f5b9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b3-b1-b1-Input_StartDate&quot;)</value>
      <webElementGuid>d2955dda-eac4-4f24-a9a5-1f64a1159a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b3-b1-b1-Input_StartDate']</value>
      <webElementGuid>cffe4bf0-8bf8-4eed-9d16-63659605f1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b3-b1-$b1']/div/div/div[2]/span/input</value>
      <webElementGuid>83187e1c-dd07-438d-bba3-3d4edc351aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/div/div/div[2]/span/input</value>
      <webElementGuid>86203d43-7470-4a2f-9e5f-257496819869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-b1-Input_StartDate']</value>
      <webElementGuid>721b997a-0487-4dec-a3c2-e6463e281d09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
