<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ShowroomSupplier</name>
   <tag></tag>
   <elementGuidId>3c06a4be-d3a3-4b22-9f59-eaf0995c7da3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.last-sub-menu-link.OSFillParent.active > span.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5438b6df-9666-421e-8271-e4a8fa962fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_MarginGutter</value>
      <webElementGuid>f46ce36e-f522-4f9e-9794-d16c81e11dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showroom/Supplier</value>
      <webElementGuid>84a9a812-7f36-4bcd-a4e1-8c096bb9e991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-28_7-b4-l1-41_4-$b2&quot;)/div[@class=&quot;list list-group OSFillParent&quot;]/a[@class=&quot;last-sub-menu-link OSFillParent active&quot;]/span[@class=&quot;ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>e286b591-4dc4-483b-b5fd-35b17a8c005d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-28_7-b4-l1-41_4-$b2']/div/a[3]/span</value>
      <webElementGuid>48f0a0cf-b2c2-45a3-93a7-3f52960ce4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/following::span[1]</value>
      <webElementGuid>74f780a2-1c55-434d-8668-0d1ac037e065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Golive'])[1]/following::span[2]</value>
      <webElementGuid>ebeeaecd-2c90-4c53-8daf-c302eab1c3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operasional Cabang'])[1]/preceding::span[2]</value>
      <webElementGuid>dbcf2228-42b6-4bd3-b0ce-025866145946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemeriksaan Petty Cash'])[1]/preceding::span[4]</value>
      <webElementGuid>f13de835-298a-42c1-b71d-af97f4018e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showroom/Supplier']/parent::*</value>
      <webElementGuid>96c6dcf2-5298-4773-939c-2bc709e9e773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/span</value>
      <webElementGuid>7ed4540a-bc9e-4295-aae2-a9b647a36bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Showroom/Supplier' or . = 'Showroom/Supplier')]</value>
      <webElementGuid>58300447-8f7c-4227-ae5e-1ecaa0b6b65d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
