<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Akuisisi</name>
   <tag></tag>
   <elementGuidId>0365c866-1565-4e9a-ae51-dc272014deaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b2-l1-28_7-b4-l1-41_4-b1-Menu > span.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring &amp; Review'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21691a98-59a0-43c6-861c-7fe1fc19d9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_MarginGutter</value>
      <webElementGuid>0d942c66-fbe6-4b98-88bf-c1ef2f8f9023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akuisisi</value>
      <webElementGuid>02910814-af55-4380-aa54-abfdb8522689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2-l1-28_7-b4-l1-41_4-b1-Menu&quot;)/span[@class=&quot;ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>9826fa82-7833-4dee-b2b7-ea3f97a73d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b2-l1-28_7-b4-l1-41_4-b1-Menu']/span</value>
      <webElementGuid>5a150b3b-51e1-45d3-be69-7a1304c05c9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoring &amp; Review'])[1]/following::span[2]</value>
      <webElementGuid>b2a03b56-f4cf-41c2-9720-77128a3173b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::span[5]</value>
      <webElementGuid>f14fa200-944e-4feb-a499-340a9ee511a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Golive'])[1]/preceding::span[2]</value>
      <webElementGuid>12423353-86fc-4cf0-b647-d644c68a8e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy Contract'])[1]/preceding::span[3]</value>
      <webElementGuid>bc0f7de8-3325-4907-9609-abfcd29a8455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akuisisi']/parent::*</value>
      <webElementGuid>7cef52cb-763e-4432-8e17-b1b512955839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/div/span</value>
      <webElementGuid>44051156-62c6-48b6-a9af-4770e9dbb884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Akuisisi' or . = 'Akuisisi')]</value>
      <webElementGuid>83e6793c-1c47-4f80-8f38-66370400eb31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
