<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TenggatWaktuPenyelesaian</name>
   <tag></tag>
   <elementGuidId>6a672104-9755-427c-933d-a93589bb9933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div/div/div/div/div/div[3]/div/div/div[3]/div/div[2]/table/tbody/tr[1]/td[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-required=&quot;true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e3eed9a-7547-48af-9158-6dbb5638602e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ThemeGrid_Width4</value>
      <webElementGuid>3c0eb26a-e3b1-4139-baed-e4d193166aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>b454eed6-05a4-405e-8b79-53050d900994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00df236e-2f06-4324-984b-a3786ca60209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>2026-07-14</value>
      <webElementGuid>d1e733f0-806d-4f3d-8ade-7a6bb8eb14a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b3-b1-TanggatWaktuValue</value>
      <webElementGuid>6bdf49f7-e1d1-4bc4-917a-0f6139dea28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-636059f55691eb6b6fd3db9ed640e633</value>
      <webElementGuid>1b35c158-7924-462c-ace6-41e3d2069df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-required = 'true']</value>
      <webElementGuid>4644b2ea-ef91-4fa8-b2fc-443d4ba2165e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-required = 'true']</value>
      <webElementGuid>cfa83711-67d1-4e6f-8283-788c86981442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'b3-b1-TanggatWaktuValue']</value>
      <webElementGuid>7a604cbc-cc7e-4b31-8a55-14942037eea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
